import type { LevelPlayTutorialStepConfig } from "@/features/level/tutorial/types";

/**
 * Reihenfolge und Texte des Spieltutorials; Ziele sind die benannten Elemente der Spieloberfläche.
 */
export const LEVEL_PLAY_TUTORIAL_STEPS: LevelPlayTutorialStepConfig[] = [
  {
    id: "library-intro",
    target: "tileLibrary",
    speechBubbleTarget: "tileLibraryStrip",
    message: "Alle möglichen Puzzleteile für die Mission.",
    primaryButtonLabel: "Alles klar!",
    bubblePlacement: "aboveTarget",
    pointer: "bottom",
    bubbleGap: -50,
    highlightPadding: 6,
    highlightRingBorderRadius: "0.5rem",
    highlightAllLibraryPieces: true,
    libraryPieceHighlightPadding: 6,
    showPrimaryHighlightRing: false,
    highlightPulse: false,
    secondaryHighlightPulse: true,
    dimOverlay: true,
    advance: { type: "primaryButton" },
  },
  {
    id: "mission-progress-intro",
    target: "headerMissionProgress",
    message: "Fülle die Schwammstadt-Powerleiste mit Punkten, um zu gewinnen.",
    primaryButtonLabel: "Alles klar!",
    bubblePlacement: "belowTarget",
    pointer: "top",
    highlightPadding: 8,
    highlightPulse: true,
    dimOverlay: true,
    advance: { type: "primaryButton" },
  },
  {
    id: "puzzle-moves-intro",
    target: "puzzleCountBadge",
    message: "Erfülle die Mission in {{maxPuzzleItems}} Zügen",
    primaryButtonLabel: "Alles klar!",
    bubblePlacement: "aboveTarget",
    pointer: "bottom",
    bubbleGap: -70,
    highlightPadding: 6,
    highlightPulse: true,
    dimOverlay: true,
    advance: { type: "primaryButton" },
  },
  {
    id: "library-tap-piece",
    target: "tileCardsButton",
    speechBubbleTarget: "tileLibrary",
    message:
      "Je besser eine Maßnahme zur Mission passt, desto mehr Punkte bekommst du.\n\n**Schau dir die Schwammstadt-Power der Puzzleteile an.**",
    bubblePlacement: "aboveTarget",
    pointer: "bottom",
    bubbleGap: 170,
    highlightPadding: 8,
    highlightRingBorderRadius: "9999px",
    bubblePointerHorizontalAlign: "right",
    highlightPulse: true,
    dimOverlay: true,
    advance: { type: "detailClosed" },
  },
  {
    id: "drag-to-board",
    target: "gameBoard",
    speechBubbleTarget: "tileLibrary",
    puzzlePieceIndex: 0,
    message:
      "Ziehe ein Puzzleteil ins Spielfeld und finde die richtige Stelle.",
    bubblePlacement: "aboveTarget",
    pointer: "bottom",
    bubbleGap: 10,
    highlightPadding: 0,
    showDragHandIllustration: true,
    bubbleContentRow: true,
    highlightAllLibraryPieces: true,
    libraryPieceHighlightPadding: 6,
    highlightRingBorderRadius: "0.5rem",
    extraHighlightTargets: ["puzzleCountBadge"],
    showPrimaryHighlightRing: false,
    highlightPulse: false,
    secondaryHighlightPulse: true,
    dimOverlay: true,
    advance: { type: "dragReleased" },
  },
];
