import yeahMp3Url from "@/internal_assets/sounds/yeah.mp3";
import type { SoundDefinition, SoundId } from "@/lib/sound/soundTypes";

export const SOUND_REGISTRY: Record<SoundId, SoundDefinition> = {
  "button.click": {
    kind: "generated",
    volume: 0.16,
    steps: [
      {
        type: "sine",
        frequency: 12050,
        durationMs: 7,
        attackMs: 1,
        releaseMs: 6,
        volume: 0.42,
      },
      {
        type: "sine",
        frequency: 8700,
        durationMs: 7,
        attackMs: 1,
        releaseMs: 6,
        volume: 0.38,
      },
      {
        type: "triangle",
        frequency: 1700,
        durationMs: 7,
        delayMs: 1,
        attackMs: 1,
        releaseMs: 5,
        volume: 0.2,
      },
      {
        type: "triangle",
        frequency: 565,
        durationMs: 6,
        delayMs: 1,
        attackMs: 1,
        releaseMs: 5,
        volume: 0.08,
      },
    ],
  },
  "puzzle.pickup": {
    kind: "generated",
    volume: 0.24,
    steps: [
      {
        type: "sine",
        frequency: 12050,
        durationMs: 7,
        attackMs: 1,
        releaseMs: 6,
        volume: 0.42,
      },
      {
        type: "sine",
        frequency: 8700,
        durationMs: 7,
        attackMs: 1,
        releaseMs: 6,
        volume: 0.38,
      },
      {
        type: "triangle",
        frequency: 1700,
        durationMs: 7,
        delayMs: 1,
        attackMs: 1,
        releaseMs: 5,
        volume: 0.2,
      },
      {
        type: "triangle",
        frequency: 565,
        durationMs: 6,
        delayMs: 1,
        attackMs: 1,
        releaseMs: 5,
        volume: 0.08,
      },
    ],
  },
  "puzzle.place": {
    kind: "generated",
    volume: 0.28,
    steps: [
      // weicher Plopp beim Ablegen
      {
        type: "sine",
        frequency: 220,
        durationMs: 48,
        attackMs: 4,
        releaseMs: 44,
        volume: 0.36,
      },
      {
        type: "sine",
        frequency: 340,
        durationMs: 34,
        delayMs: 24,
        attackMs: 2,
        releaseMs: 36,
        volume: 0.28,
      },

      // Einrasten
      {
        type: "triangle",
        frequency: 520,
        durationMs: 30,
        delayMs: 78,
        attackMs: 1,
        releaseMs: 32,
        volume: 0.24,
      },

      // positive Bestätigung: kleiner Aufwärtsklang
      {
        type: "sine",
        frequency: 660,
        durationMs: 52,
        delayMs: 118,
        attackMs: 3,
        releaseMs: 56,
        volume: 0.22,
      },
      {
        type: "sine",
        frequency: 880,
        durationMs: 70,
        delayMs: 156,
        attackMs: 4,
        releaseMs: 76,
        volume: 0.16,
      },
    ],
  },
  "puzzle.invalid": {
    kind: "generated",
    volume: 0.18,
    steps: [
      // dumpfer Gluck
      {
        type: "sine",
        frequency: 260,
        durationMs: 54,
        attackMs: 4,
        releaseMs: 50,
        volume: 0.34,
      },
      {
        type: "sine",
        frequency: 190,
        durationMs: 62,
        delayMs: 42,
        attackMs: 5,
        releaseMs: 58,
        volume: 0.32,
      },

      // kleines Wobble / Abrutschen
      {
        type: "triangle",
        frequency: 310,
        durationMs: 42,
        delayMs: 94,
        attackMs: 3,
        releaseMs: 44,
        volume: 0.22,
      },
      {
        type: "sine",
        frequency: 230,
        durationMs: 70,
        delayMs: 130,
        attackMs: 4,
        releaseMs: 72,
        volume: 0.24,
      },
    ],
  },
  "points.collect": {
    kind: "generated",
    volume: 0.18,
    steps: [
      {
        type: "triangle",
        frequency: 400,
        durationMs: 40,
        attackMs: 1,
        releaseMs: 31,
        volume: 0.23,
      },
      {
        type: "triangle",
        frequency: 630,
        durationMs: 34,
        delayMs: 40,
        attackMs: 1,
        releaseMs: 27,
        volume: 0.6,
      },
      {
        type: "triangle",
        frequency: 920,
        durationMs: 36,
        delayMs: 70,
        attackMs: 1,
        releaseMs: 28,
        volume: 0.72,
      },
      {
        type: "triangle",
        frequency: 1145,
        durationMs: 34,
        delayMs: 110,
        attackMs: 1,
        releaseMs: 27,
        volume: 0.48,
      },
      {
        type: "triangle",
        frequency: 1375,
        durationMs: 33,
        delayMs: 149,
        attackMs: 1,
        releaseMs: 26,
        volume: 0.32,
      },
      {
        type: "triangle",
        frequency: 1605,
        durationMs: 32,
        delayMs: 189,
        attackMs: 1,
        releaseMs: 25,
        volume: 0.22,
      },
      {
        type: "triangle",
        frequency: 1835,
        durationMs: 31,
        delayMs: 229,
        attackMs: 1,
        releaseMs: 24,
        volume: 0.15,
      },
      {
        type: "triangle",
        frequency: 2065,
        durationMs: 30,
        delayMs: 268,
        attackMs: 1,
        releaseMs: 23,
        volume: 0.1,
      },
      {
        type: "triangle",
        frequency: 2295,
        durationMs: 29,
        delayMs: 308,
        attackMs: 1,
        releaseMs: 22,
        volume: 0.066,
      },
      {
        type: "triangle",
        frequency: 2525,
        durationMs: 28,
        delayMs: 348,
        attackMs: 1,
        releaseMs: 21,
        volume: 0.044,
      },
      {
        type: "triangle",
        frequency: 2750,
        durationMs: 27,
        delayMs: 387,
        attackMs: 1,
        releaseMs: 20,
        volume: 0.03,
      },
      {
        type: "triangle",
        frequency: 2980,
        durationMs: 26,
        delayMs: 427,
        attackMs: 1,
        releaseMs: 19,
        volume: 0.02,
      },
      {
        type: "triangle",
        frequency: 3210,
        durationMs: 24,
        delayMs: 466,
        attackMs: 1,
        releaseMs: 17,
        volume: 0.012,
      },
    ],
  },
  "bonus.unlock": {
    kind: "generated",
    volume: 0.26,
    steps: [
      // erstes Wasserblubbern: etwas Erwartung
      {
        type: "sine",
        frequency: 220,
        durationMs: 56,
        attackMs: 5,
        releaseMs: 52,
        volume: 0.34,
      },
      {
        type: "sine",
        frequency: 340,
        durationMs: 38,
        delayMs: 28,
        attackMs: 3,
        releaseMs: 40,
        volume: 0.28,
      },

      // zweiter Blub, etwas heller
      {
        type: "sine",
        frequency: 280,
        durationMs: 52,
        delayMs: 92,
        attackMs: 4,
        releaseMs: 50,
        volume: 0.32,
      },
      {
        type: "triangle",
        frequency: 460,
        durationMs: 34,
        delayMs: 120,
        attackMs: 2,
        releaseMs: 38,
        volume: 0.24,
      },

      // Heller Klang zur Freischaltung.
      {
        type: "triangle",
        frequency: 720,
        durationMs: 42,
        delayMs: 178,
        attackMs: 2,
        releaseMs: 48,
        volume: 0.22,
      },
      {
        type: "sine",
        frequency: 960,
        durationMs: 64,
        delayMs: 212,
        attackMs: 4,
        releaseMs: 76,
        volume: 0.16,
      },

      // sanfter Abschluss, nicht zu triumphal
      {
        type: "sine",
        frequency: 640,
        durationMs: 90,
        delayMs: 260,
        attackMs: 8,
        releaseMs: 110,
        volume: 0.14,
      },
    ],
  },
  "bonus.unlock.map": {
    kind: "generated",
    volume: 0.24,
    steps: [
      {
        type: "sine",
        frequency: 240,
        durationMs: 44,
        attackMs: 3,
        releaseMs: 42,
        volume: 0.3,
      },
      {
        type: "sine",
        frequency: 380,
        durationMs: 36,
        delayMs: 18,
        attackMs: 2,
        releaseMs: 38,
        volume: 0.24,
      },
      {
        type: "triangle",
        frequency: 580,
        durationMs: 40,
        delayMs: 72,
        attackMs: 2,
        releaseMs: 44,
        volume: 0.22,
      },
      {
        type: "triangle",
        frequency: 820,
        durationMs: 52,
        delayMs: 118,
        attackMs: 2,
        releaseMs: 56,
        volume: 0.2,
      },
      {
        type: "sine",
        frequency: 1020,
        durationMs: 58,
        delayMs: 152,
        attackMs: 4,
        releaseMs: 64,
        volume: 0.14,
      },
      {
        type: "sine",
        frequency: 680,
        durationMs: 76,
        delayMs: 198,
        attackMs: 8,
        releaseMs: 88,
        volume: 0.11,
      },
    ],
  },
  "bonus.unlock.short": {
    kind: "generated",
    volume: 0.22,
    steps: [
      {
        type: "triangle",
        frequency: 720,
        durationMs: 36,
        attackMs: 2,
        releaseMs: 42,
        volume: 0.26,
      },
      {
        type: "sine",
        frequency: 960,
        durationMs: 52,
        delayMs: 28,
        attackMs: 3,
        releaseMs: 58,
        volume: 0.18,
      },
    ],
  },
  "quiz.correct": {
    kind: "generated",
    volume: 0.24,
    steps: [
      {
        type: "sine",
        frequency: 520,
        durationMs: 72,
        attackMs: 3,
        releaseMs: 34,
      },
      {
        type: "sine",
        frequency: 780,
        durationMs: 94,
        delayMs: 58,
        volume: 0.85,
        attackMs: 3,
        releaseMs: 44,
      },
    ],
  },
  "quiz.wrong": {
    kind: "generated",
    volume: 0.2,
    steps: [
      {
        type: "triangle",
        frequency: 260,
        durationMs: 72,
        attackMs: 3,
        releaseMs: 48,
      },
      {
        type: "triangle",
        frequency: 180,
        durationMs: 92,
        delayMs: 58,
        volume: 0.8,
        attackMs: 3,
        releaseMs: 52,
      },
    ],
  },
  "celebration.yay": {
    kind: "file",
    src: yeahMp3Url,
    volume: 0.7,
    fallback: {
      kind: "generated",
      volume: 0.32,
      steps: [
        {
          type: "triangle",
          frequency: 240,
          durationMs: 75,
          attackMs: 4,
          releaseMs: 42,
          volume: 0.75,
        },
        {
          type: "triangle",
          frequency: 320,
          durationMs: 85,
          delayMs: 55,
          attackMs: 3,
          releaseMs: 45,
          volume: 0.85,
        },
        {
          type: "triangle",
          frequency: 440,
          durationMs: 150,
          delayMs: 115,
          attackMs: 3,
          releaseMs: 95,
          volume: 1,
        },
        {
          type: "sine",
          frequency: 660,
          durationMs: 120,
          delayMs: 125,
          attackMs: 4,
          releaseMs: 85,
          volume: 0.45,
        },
      ],
    },
  },
} satisfies Record<SoundId, SoundDefinition>;
